# Generated by Django 6.0.5 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('contain', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
