# Generated by Django 6.0.5 on 2026-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=200)),
                ('contain', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='model_QA/')),
            ],
        ),
    ]
