# Generated by Django 6.0.5 on 2026-05-09 14:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_model_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
