# Generated by Django 6.0.5 on 2026-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_pdfs_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfs',
            name='file',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
